#!/usr/bin/env python

"""
Usage:

 ./find_chandra_fov ra dec radius outdir

Find all the punblically available FOV files for Chandra observations
close to the given location.

"""

import os
from pathlib import Path
import sys

from ciao_contrib.cda import data, search


def move_fov(obsid: int) -> None:
    """Move all the FOV files in obsid/*/*fov1.fits.gz to the cwd."""

    # Assume a structure to the directory
    indir = Path(str(obsid))
    for fov in indir.glob("*/*fov1.fits.gz"):
        fov.rename(fov.name)

    # Delete the directory
    #
    for dirs in indir.glob("*"):
        dirs.rmdir()

    indir.rmdir()


def find(ra: str,
         dec: str,
         radius: str,
         outdir: Path,
         allow_grating: bool = False,
            ) -> None:
    """Find all FOV files within the given code and write them to outdir.

    """

    ra0 = float(ra)
    dec0 = float(dec)
    rad0 = float(radius)

    print(f"Searching Chandra archive ra={ra0} dec={dec} radius={rad0}")
    matches = search.search_chandra_archive(ra0, dec0, size=rad0)
    nmatches = len(matches)
    print(f"Found {nmatches} match(es).")
    if nmatches == 0:
        return

    if not outdir.is_dir():
        if outdir.exists():
            raise OSError(f"iutdir={outdir} exists and is not a directory")

        outdir.mkdir()

    print("Downloading FOV files:")
    olddir = outdir.cwd()
    seen = set()
    try:
        os.chdir(outdir)

        for idx, (obsid, grating, simode) in enumerate(zip(matches["ObsId"],
                                                           matches["Grating"],
                                                           matches["SIMode"]),
                                                       1):

            # In case duplicates are possible
            if obsid in seen:
                continue

            seen.add(obsid)

            # Do we disallow grating data?
            if not allow_grating and grating != 'NONE':
                continue

            # Disallow CC-mode. Should we also drop any non-DEFAULT
            # settings for HRC data?
            #
            if simode.startswith('CC'):
                continue

            data.download_chandra_obsids([obsid], ["fov"])
            move_fov(int(obsid))

            if idx % 10 == 0:
                sys.stdout.write(".")
            if idx % 70 == 0:
                sys.stdout.write("\n")

            sys.stdout.flush()

        sys.stdout.write("\n")
        sys.stdout.flush()

    finally:
        os.chdir(olddir)

    print(f"Downloaded {len(seen)} FOV files.")


if __name__ == "__main__":

    import argparse
    p = argparse.ArgumentParser(
        prog='find_chandra_fov',
        description='Download Chandra FOV files to outdir')

    p.add_argument('ra', help="RA center in decimal degrees")
    p.add_argument('dec', help="Dec center in decimal degrees")
    p.add_argument('radius', help="Radius in decimal degrees")
    p.add_argument('outdir', help="Location to store the FOV files")

    p.add_argument('--grating', action="store_true",
                   help="Include grating observations")

    args = p.parse_args()
    find(args.ra, args.dec, args.radius, Path(args.outdir),
         allow_grating=args.grating)
